export const ROUTES = {
  HOME: '/',
  DASHBOARD: '/dashboard',
  PUBLIC_FORMS: '/public-forms',
  CREATE_FORM: '/create-form',
  CREATE_FORMS_NEW: '/create-form-new',
  FORM_FILLER: '/form/:formId',
  FORM_FILLER_OLD: '/form-old/:formId',
  FORM_FILLER_NEW: '/form-new/:formId',
  EDIT_FORM_SECRET: '/edit/:formId/:secret',
  PREVIEW: '/preview/:formId',
  RESPONSES: '/responses/:formId',
  RESPONSES_NEW: '/responses-new/:formId',
  RESPONSES_SECRET: '/responses/:formId/:secret',
  DRAFT: '/draft/:draftId',
  EMBEDDED: '/embed/:formId',
  PROFILE: '/profile',
  MY_FORMS: '/my-forms',
  MY_RESPONSES: '/my-responses',
  SETTINGS: '/settings',
  NOTIFICATIONS: '/notifications'
};